### ISSUE TITLE
Image paths to be corrected

### ISSUE THREAD

**Issue by ramezrafla** [marcelklehr/socialcalc#18]
In the constants file, there are many references to `sc-<something>.gif`, when the images folder follows `sc_<something>.gif`

-- Just documenting, feel free to ignore

**Comment by eddyparkinson** [comment]
**History**  marcelklehr/socialcalc was split out to add OTs. It used to be part of audreyt/ethercalc
I am guessing a few things in marcelklehr/socialcalc don't work unless they are used with ethercalc.

**Constants** 
Most of the values in the constants file are no longer used. 
They were replaced by the files in https://github.com/audreyt/ethercalc/tree/master/l10n
 before marcelklehr/socialcalc  was created.   

Old  https://github.com/marcelklehr/socialcalc/blob/master/socialcalcconstants.js#L144
New https://github.com/audreyt/ethercalc/blob/master/l10n/en.json#L25

**Comment by ramezrafla** [comment]
Thanks, but i noticed the error because of a console log. When i changed the values in the Constants file it fixed things. Are we sure this repo is up to date?

**Comment by eddyparkinson** [comment]
Do you want me to re-open? 

The correct values exist in ethercalc, but you are welcome to fix things here if you want.
Also, better icons exist in ethercalc.  It is hard to say how many issues you will find by using marcelklehr/socialcalc
without ethercalc.  e.g. ethercalc runs socialcalc on the server to minimise data traffic, data exports and the API are in ethercalc.

**Comment by marcelklehr** [comment]
I guess this could be considered a duplicate of #4, which would be a good improvement, imo. I think this repo should contain everything necessary or directly useful to running socialcalc in a different environment than ethercalc.

**Comment by ramezrafla** [comment]
>  I think this repo should contain everything necessary or directly useful to running socialcalc in a different environment than ethercalc.

Agreed, and right now there are extra steps to make it work as expected. For instance, the sheet starts in what seems to be an unstable mode where we can only edit cell A1. We have to programmatically select tab "edit" to get normal behavior.

My concern right now is that we have to do a lot of work to make it have a normal usable scenario, and will start to use our choices of styling and frameworks -- so we will have **our own fork** which may not be compatible with your design choices for ethercalc. For example, the CSS is global (I would expect all the CSS selectors to be preceded with something like `.sheet`) which means it was meant to be a drop-in in another app.

**Comment by marcelklehr** [comment]
I advocate for not forking. What do you mean by design choices? I'm deferring to @audreyt on this, obviously, but my take is that probably anything you would do to improve socialcalc would benefit ethercalc as well and they would be happy to integrate those changes, the only problem being that someone has to update ethercalc to use the new APIs and stuff, but as there's not much else happening here atm, afaik, I'd say ethercalc could link to a fixed version of socialcalc and we could pull any pull requests you're shooting at us. It might even make sense to simply have a new version branch for the new features and fixes and keep the 2.x branch open for hotfixes and stuff.

**Comment by ramezrafla** [comment]
I missed this comment above by @marcelklehr 
Are you all OK if we use Semantic-UI as a framework?

The problem is that without a framework there is so much duplication of code and serious dissimilarity in look and feel (for example: the popups, buttons, icons etc.) when you include in an app -- which is what we are doing.

Let me set up our app with SocialCalc built-in and send you credentials and you can judge.
