### ISSUE TITLE
Cells are inactive and scrolls bars not visible in the initial load

### ISSUE THREAD

**Issue by sura2k** [marcelklehr/socialcalc#27]
**Initial load**
![image](https://user-images.githubusercontent.com/1226939/31188842-ff7470a8-a953-11e7-9ba7-8fa55e2dbdf4.png)

**When I click on any button ("Ex:  Format, Sort, tabs) or press enter in a text box, it comes back to normal as expected.**
![image](https://user-images.githubusercontent.com/1226939/31188922-3d4afce4-a954-11e7-9a3c-de022604a107.png)

**Integration**
I just added a HTML page into the same source in the master branch and put the 2 lines as you guided in the README.
```
<body>
	<div id="app"></div>
	
	<script src="./libs/jquery.js"></script>
	<script src="SocialCalc.js"></script>
	<script>
		var socialCalcControl = new SocialCalc.SpreadsheetControl();
		socialCalcControl.InitializeSpreadsheetControl("app" /*, height, width, spacebelow*/);
	</script>
</body>
```
If I get a solution to cell inactivity, I can live with scroll bar issue at the moment.
Any help appreciated.

Note: I'm only interested in the SocialCal UI and not about the EtherCalc, but EtherCalc has no such issue.

**Comment by marcelklehr** [comment]
Without having tried it, two things come to my mind:

 * wait for document#onload, provided by jquery
 * you could schedule a recalculate sheet command on init as well, see https://github.com/gulf/gulf-editor-socialcalc/blob/master/src/index.js#L45

**Comment by sura2k** [comment]
'recalc' worked. Thanks!

**Comment by marcelklehr** [comment]
Awesome, I'm glad it works :)
