### ISSUE TITLE
Make a npm release

### ISSUE THREAD

**Issue by audreyt** [marcelklehr/socialcalc#48]
The previous npm release (2.2.0) was two years ago; there's been quite some fixes since then, notably around exception handling in `IF` function.

While I've updated `ethercalc` package to point to this GitHub repository, it would be awesome to make a release (2.3.0 perhaps?) to collect the changes so far.

**Comment by marcelklehr** [comment]
Two years already?! wow. I'll get on it :)

**Comment by marcelklehr** [comment]
Let me know if this works: https://www.npmjs.com/package/socialcalc

I think you are also allowed to publish, btw ;)
