### ISSUE TITLE
Published package 2.1.0 does not match tag v2.1.0

### ISSUE THREAD

**Issue by atifaziz** [marcelklehr/socialcalc#6]
I install the package:

```
npm i socialcalc@v2.1.0
```

I clone the repo:

```
https://github.com/marcelklehr/socialcalc.git
```

I checkout tag v2.1.0:

```
cd socialcalc
git checkout v2.1.0
```

I do a diff:

```
diff SocialCalc.js ../node_modules/socialcalc/SocialCalc.js
```

I get over 80 differences. See [diff.zip](https://github.com/marcelklehr/socialcalc/files/383168/diff.zip) for more.

**Comment by eddyparkinson** [comment]
Suggest you use github version if you want the latest. I did a push to github last week, so most of the differences will be mine. (the changes allow people to build webapps with spreadsheet formulas)

Note: marcelklehr/ot-socialcalc  should replace marcelklehr/socialcalc when all is stable.

**Comment by atifaziz** [comment]
@eddyparkinson Trouble is [ethercalc depends on 2.x](https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/package.json#L20) and I'm trying to track down a potential issue in SocialCalc that starts life in audreyt/ethercalc#411.

> Suggest you use github version if you want the latest.

Not looking for the latest version but the latest release.

**Comment by eddyparkinson** [comment]
npm can pull from github - see https://docs.npmjs.com/files/package.json#dependencies

Note, until a few months ago, "marcelklehr/socialcalc" was part of  audreyt/ethercalc it was split out
 to help with the mutiuser data corruption issue  that is being fixed in marcelklehr/ot-socialcalc 

Yes the "loadclipboard" does look to need a clean up. - I fixed a few bugs in it months ago, as it was not working at all.

**Comment by atifaziz** [comment]
@eddyparkinson Thanks for the history on how the various repos are evolving. So would this still be the right repo for any fixex and contributions SocialCalc?

> npm can pull from github - see https://docs.npmjs.com/files/package.json#dependencies

Am aware of that option. Point of raising this issue was to point out the inconsistency between the tagged and published version and get confirmation about whether what I'm seeing was intended or an accident. The inconsistency makes knowing the state of affairs difficult when you're setting up for debugging and potentially fixing an issue. I didn't want to debug/fix an issue in the wrong version.

An action to this issue would be to add a note to the [v2.1.0 release](https://github.com/marcelklehr/socialcalc/releases/tag/v2.1.0) that spells out the real commit hash that was published to the NPM registry. If that's too much trouble then just drop it here and close the issue. :)

**Comment by marcelklehr** [comment]
Hello @atifaziz! This is probably an error on my account. `SocialCalc.js` is generated by the Makefile (by concatenating most of the other files). This is a relic from the past where there were no js modules. The drawback today is that the maintainer has to remember to run `make` before release a new version, which I, apparently, forgot. Sorry for that and thank you for reaching out!

**Comment by marcelklehr** [comment]
I just released v2.2.0 with the latest changes by @eddyparkinson. Oh, and yes, this is the right repo to send pull requests to (looking forward to that! :star2:).

**Comment by atifaziz** [comment]
@marcelklehr Thanks for the explanation and publishing the new release.

**Comment by atifaziz** [comment]
@marcelklehr Just checked out and can confirm that [v2.2.0](https://github.com/marcelklehr/socialcalc/releases/tag/v2.2.0) matches the published package. Thanks for taking care of this. 👍 Now I know I'll be working of the right sources. 😃

**Comment by atifaziz** [comment]
> this is the right repo to send pull requests to (looking forward to that! 🌟).

Done already. See PR #5 for a gentle start.

**Comment by marcelklehr** [comment]
Ah, that seems to have fallen through the cracks of my inbox. Merged. :)
